### ISSUE TITLE
The links in README need to be updated

### ISSUE THREAD

**Issue by CodinCat** [CodeIgniter-TW/CodeIgniter-UserGuide#1]
http://codeigniter.org.tw
must have "www"
http://www.codeigniter.org.tw

and new official website:
http://ellislab.com/codeigniter

**Comment by appleboy** [comment]
Hi @MrOPR,

I already setup the codeigniter.org.tw url redirect to www.codeigniter.org.tw

**Comment by appleboy** [comment]
Update the DNS record, please wait 24 hour.
