### ISSUE TITLE
看到似乎有錯字，小弟來回報一下

### ISSUE THREAD

**Issue by LouisXXL** [CodeIgniter-TW/CodeIgniter-UserGuide#102]
**_一般主題->helpers_**
[http://i.imgur.com/5eWTC4B.jpg](url)

> 請注意所有的原生 CodeIgniter 函式庫的`前綴事` CI_ 所以不要使用這個字串當做你的前綴。

**_一般主題->透過CLl執行codeigniter_**
[http://imgur.com/bmKDSLP.jpg](url)

> 現在您可以透過瀏覽器`觀鍵`入底下網址：

**_一般主題->替代 View 檔案的 PHP 的語法_**
[http://imgur.com/W6tNz3B.jpg](url)

> 也請注意到，在每個結構之後（除了最後一個）不使用的分號（;），而是冒號（:）。這很容易`稿錯`，這個非常重要！

**Comment by appleboy** [comment]
@LouisXXL I got it.
