### ISSUE TITLE
Found an error in libraries/email Class

### ISSUE THREAD

**Issue by sixsckert** [CodeIgniter-TW/CodeIgniter-UserGuide#112]
Hey guys,
I found an error on website page: https://codeigniter.org.tw/userguide3/libraries/email.html
The example code in `attachment_cid($filename)`:

>$cid = $this->email->attach_cid($filename);
>$this->email->message('<img src="cid:"' $cid .'" alt="photo1" />');

Change `attach_cid()` into `attachment_cid()` , and there's missing a dot before `$cid`. 
:D

**Comment by appleboy** [comment]
Thanks for your reminder. I will fix this issue asap.
