### ISSUE TITLE
3.1.4 跟 3.1.5 檔案不存在

### ISSUE THREAD

**Issue by RicherYang** [CodeIgniter-TW/CodeIgniter-UserGuide#118]
[下載頁面](https://codeigniter.org.tw/userguide3/installation/downloads.html) 已經更新至 3.1.5 版本。
但是實際上伺服器中的檔案最新版本只有到 3.1.3 ，請在協助補上 3.1.4 跟 3.1.5 的檔案

**Comment by appleboy** [comment]
已經處理好了，網站也更新了

https://codeigniter.org.tw/downloads
