### ISSUE TITLE
專案描述的網址 與 實際的網址不同

### ISSUE THREAD

**Issue by RicherYang** [CodeIgniter-TW/CodeIgniter-UserGuide#56]
http://codeigniter.org.tw/userguide3/installation/upgrading.html
該頁的更新內容 條列 目錄未編譯出

另，Github 上，專案描述的網址 與 實際的網址不同

**Comment by appleboy** [comment]
描述那邊我修正了，我剛剛看到未編譯出來，不知道是否格式錯了，或者是 python 有問題

我晚點再測試看看

**Comment by appleboy** [comment]
@RicherYang 格式錯誤，我已經修正

f760a26306bd05471733a354112ae845ec08b233
