### ISSUE TITLE
模板解析器連結失效

### ISSUE THREAD

**Issue by minjindang** [CodeIgniter-TW/CodeIgniter-UserGuide#81]
這邊我們輪詢每個新聞項目並顯示給使用者。你可以看到我們用 PHP 混合了 HTML 做成模板。 如果你喜歡使用模板語言，你可以使用 CodeIgniter 的 <<模板解析器>> 或其它第三方解析器。

Issue來源：
http://codeigniter.org.tw/userguide3/tutorial/news_section.html

**Comment by appleboy** [comment]
@willycode 收到。我來處理

**Comment by appleboy** [comment]
@willycode fix https://github.com/CodeIgniter-TW/CodeIgniter-UserGuide/commit/8d0a0876226249348b8ef03fbdf1c2e89e77906a
